export const Countries = {
  CN: "China",
  IN: "India",
  US: "United States",
  ID: "Indonesia",
  PK: "Pakistan",
  BR: "Brazil",
  NG: "Nigeria",
  BD: "Bangladesh",
  RU: "Russia",
  MX: "Mexico",
  JP: "Japan",
  ET: "Ethiopia",
  PH: "Philippines",
  EG: "Egypt",
  VN: "Vietnam",
  CD: "DR Congo",
  TR: "Turkey",
  IR: "Iran",
  DE: "Germany",
  TH: "Thailand",
  GB: "United Kingdom",
  FR: "France",
  IT: "Italy",
  ZA: "South Africa",
  MM: "Myanmar",
  KR: "South Korea",
  CO: "Colombia",
  ES: "Spain",
  UA: "Ukraine",
  TZ: "Tanzania",
  AR: "Argentina",
  DZ: "Algeria",
  KE: "Kenya",
  PL: "Poland",
  CA: "Canada",
  UG: "Uganda",
  MA: "Morocco",
  IQ: "Iraq",
  SD: "Sudan",
  PE: "Peru",
  MY: "Malaysia",
  UZ: "Uzbekistan",
  SA: "Saudi Arabia",
  NP: "Nepal",
  VE: "Venezuela",
  GH: "Ghana",
  YE: "Yemen",
  AF: "Afghanistan",
  MZ: "Mozambique",
  CM: "Cameroon",
  CI: "Côte d'Ivoire",
  MG: "Madagascar",
  AU: "Australia",
  KP: "North Korea",
  TW: "Taiwan",
  NE: "Niger",
  LK: "Sri Lanka",
  RO: "Romania",
  ML: "Mali",
  SY: "Syria",
  KZ: "Kazakhstan",
  KH: "Cambodia",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  TD: "Chad",
  GN: "Guinea",
  SS: "South Sudan",
  RW: "Rwanda",
  SN: "Senegal",
  SO: "Somalia",
  BJ: "Benin",
  HT: "Haiti",
  BO: "Bolivia",
  BF: "Burkina Faso",
  DO: "Dominican Republic",
  CZ: "Czech Republic",
  GR: "Greece",
  JO: "Jordan",
  TN: "Tunisia",
  GT: "Guatemala",
  SE: "Sweden",
  AE: "United Arab Emirates",
  AZ: "Azerbaijan",
  BY: "Belarus",
  SL: "Sierra Leone",
  TJ: "Tajikistan",
  AT: "Austria",
  HU: "Hungary",
  CH: "Switzerland",
  IL: "Israel",
};
